[package]
name = "cube"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0"
bytemuck = { version = "1.24", features = ["derive"] }
glam = "0.33.2"
log = "0.4"
wgpu = "29.0"
winit = "0.30.13"

[dependencies.image]
version = "0.24"
default-features = false
features = ["jpeg"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.10"
pollster = "0.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1"
console_log = "1.0"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-time = "1.1"

[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3"
features = ["Document", "Element", "HtmlCanvasElement", "HtmlElement", "Window"]
