[package]
name = "wgpu-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.103"
bytemuck = "1.25.1"
env_logger = "0.11.11"
glam = "0.33.2"
gltf = "1.4.1"
log = "0.4.33"
slotmap = "1.1.1"
web-time = "1.1.0"
# Pin to v29 due to this bug https://github.com/gfx-rs/wgpu/issues/9855
wgpu = "29.0"

[dependencies.image]
version = "0.24"
default-features = false
features = ["jpeg", "png"]
