[package]
name = "luxa"
version = "0.0.1"
edition = "2024"

[dependencies]
anyhow = "1.0.103"
bytemuck = "1.25.1"
glam = "0.33.2"
gltf = "1.4.1"
log = "0.4.33"
slotmap = "1.1.1"
web-time = "1.1.0"
# Pin to v29 due to this bug https://github.com/gfx-rs/wgpu/issues/9855
wgpu = "29.0"
half = { version = "2.7.1", features = ["bytemuck"] }

[dependencies.image]
version = "0.24"
default-features = false
features = ["jpeg", "png", "hdr"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.11.11"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3", features = ["HtmlCanvasElement"] }
